export enum Permiso {
  // Usuarios
  GESTIONAR_USUARIOS = 'GESTIONAR_USUARIOS',
  VER_USUARIOS = 'VER_USUARIOS',

  // Clientes
  GESTIONAR_CLIENTES = 'GESTIONAR_CLIENTES',
  VER_CLIENTES = 'VER_CLIENTES',

  // Obligaciones
  GESTIONAR_OBLIGACIONES = 'GESTIONAR_OBLIGACIONES',
  VER_OBLIGACIONES = 'VER_OBLIGACIONES',

  // Contabilidad
  GESTIONAR_CONTABILIDAD = 'GESTIONAR_CONTABILIDAD',
  VER_CONTABILIDAD = 'VER_CONTABILIDAD',

  // Nomina
  GESTIONAR_NOMINA = 'GESTIONAR_NOMINA',
  VER_NOMINA = 'VER_NOMINA',

  // Documentos
  GESTIONAR_DOCUMENTOS = 'GESTIONAR_DOCUMENTOS',
  VER_DOCUMENTOS = 'VER_DOCUMENTOS',

  // Tareas
  GESTIONAR_TAREAS = 'GESTIONAR_TAREAS',
  VER_TAREAS = 'VER_TAREAS',

  // Facturacion
  GESTIONAR_FACTURACION = 'GESTIONAR_FACTURACION',
  VER_FACTURACION = 'VER_FACTURACION',

  // Configuracion
  GESTIONAR_CONFIGURACION = 'GESTIONAR_CONFIGURACION',

  // Portal cliente
  VER_PROPIOS_DATOS = 'VER_PROPIOS_DATOS',
  VER_PROPIOS_DOCUMENTOS = 'VER_PROPIOS_DOCUMENTOS',
  VER_PROPIOS_VENCIMIENTOS = 'VER_PROPIOS_VENCIMIENTOS',
}
